/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachProgramsRouteImport } from './routes/coach.programs'
import { Route as CoachExercisesRouteImport } from './routes/coach.exercises'
import { Route as CoachDashboardRouteImport } from './routes/coach.dashboard'
import { Route as CoachProgramsIndexRouteImport } from './routes/coach.programs.index'
import { Route as CoachProgramsProgramIdRouteImport } from './routes/coach.programs.$programId'
import { Route as CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport } from './routes/coach.programs.$programId.workouts.$workoutId'
import { Route as CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport } from './routes/coach.programs.$programId.workouts.$workoutId.preview'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProgramsRoute = CoachProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => CoachRoute,
} as any)
const CoachExercisesRoute = CoachExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => CoachRoute,
} as any)
const CoachDashboardRoute = CoachDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CoachRoute,
} as any)
const CoachProgramsIndexRoute = CoachProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachProgramsRoute,
} as any)
const CoachProgramsProgramIdRoute = CoachProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => CoachProgramsRoute,
} as any)
const CoachProgramsProgramIdWorkoutsWorkoutIdRoute =
  CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport.update({
    id: '/workouts/$workoutId',
    path: '/workouts/$workoutId',
    getParentRoute: () => CoachProgramsProgramIdRoute,
  } as any)
const CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute =
  CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => CoachProgramsProgramIdWorkoutsWorkoutIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/programs': typeof CoachProgramsRouteWithChildren
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRouteWithChildren
  '/coach/programs/': typeof CoachProgramsIndexRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRouteWithChildren
  '/coach/programs': typeof CoachProgramsIndexRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/programs': typeof CoachProgramsRouteWithChildren
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRouteWithChildren
  '/coach/programs/': typeof CoachProgramsIndexRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/sitemap.xml'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/coach/programs'
    | '/coach/programs/$programId'
    | '/coach/programs/'
    | '/coach/programs/$programId/workouts/$workoutId'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/sitemap.xml'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/coach/programs/$programId'
    | '/coach/programs'
    | '/coach/programs/$programId/workouts/$workoutId'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/sitemap.xml'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/coach/programs'
    | '/coach/programs/$programId'
    | '/coach/programs/'
    | '/coach/programs/$programId/workouts/$workoutId'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/programs': {
      id: '/coach/programs'
      path: '/programs'
      fullPath: '/coach/programs'
      preLoaderRoute: typeof CoachProgramsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/exercises': {
      id: '/coach/exercises'
      path: '/exercises'
      fullPath: '/coach/exercises'
      preLoaderRoute: typeof CoachExercisesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/dashboard': {
      id: '/coach/dashboard'
      path: '/dashboard'
      fullPath: '/coach/dashboard'
      preLoaderRoute: typeof CoachDashboardRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/programs/': {
      id: '/coach/programs/'
      path: '/'
      fullPath: '/coach/programs/'
      preLoaderRoute: typeof CoachProgramsIndexRouteImport
      parentRoute: typeof CoachProgramsRoute
    }
    '/coach/programs/$programId': {
      id: '/coach/programs/$programId'
      path: '/$programId'
      fullPath: '/coach/programs/$programId'
      preLoaderRoute: typeof CoachProgramsProgramIdRouteImport
      parentRoute: typeof CoachProgramsRoute
    }
    '/coach/programs/$programId/workouts/$workoutId': {
      id: '/coach/programs/$programId/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/coach/programs/$programId/workouts/$workoutId'
      preLoaderRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport
      parentRoute: typeof CoachProgramsProgramIdRoute
    }
    '/coach/programs/$programId/workouts/$workoutId/preview': {
      id: '/coach/programs/$programId/workouts/$workoutId/preview'
      path: '/preview'
      fullPath: '/coach/programs/$programId/workouts/$workoutId/preview'
      preLoaderRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport
      parentRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRoute
    }
  }
}

interface CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren {
  CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
}

const CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren: CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren =
  {
    CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute:
      CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute,
  }

const CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren =
  CoachProgramsProgramIdWorkoutsWorkoutIdRoute._addFileChildren(
    CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren,
  )

interface CoachProgramsProgramIdRouteChildren {
  CoachProgramsProgramIdWorkoutsWorkoutIdRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
}

const CoachProgramsProgramIdRouteChildren: CoachProgramsProgramIdRouteChildren =
  {
    CoachProgramsProgramIdWorkoutsWorkoutIdRoute:
      CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren,
  }

const CoachProgramsProgramIdRouteWithChildren =
  CoachProgramsProgramIdRoute._addFileChildren(
    CoachProgramsProgramIdRouteChildren,
  )

interface CoachProgramsRouteChildren {
  CoachProgramsProgramIdRoute: typeof CoachProgramsProgramIdRouteWithChildren
  CoachProgramsIndexRoute: typeof CoachProgramsIndexRoute
}

const CoachProgramsRouteChildren: CoachProgramsRouteChildren = {
  CoachProgramsProgramIdRoute: CoachProgramsProgramIdRouteWithChildren,
  CoachProgramsIndexRoute: CoachProgramsIndexRoute,
}

const CoachProgramsRouteWithChildren = CoachProgramsRoute._addFileChildren(
  CoachProgramsRouteChildren,
)

interface CoachRouteChildren {
  CoachDashboardRoute: typeof CoachDashboardRoute
  CoachExercisesRoute: typeof CoachExercisesRoute
  CoachProgramsRoute: typeof CoachProgramsRouteWithChildren
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachDashboardRoute: CoachDashboardRoute,
  CoachExercisesRoute: CoachExercisesRoute,
  CoachProgramsRoute: CoachProgramsRouteWithChildren,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
